# Generated by Django 2.2.16 on 2022-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220518_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Администрирование комментария', 'verbose_name_plural': 'Администрирование комментариев'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время публикации'),
        ),
        migrations.AddField(
            model_name='follow',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время публикации'),
        ),
    ]
